duckduckgo/DaxMailer

views/email/a/FF1
=> Created FF1

views/email/a/v3.tx
Added image padding
Changed dash to em-dash
=> Visual Tweaks

views/email/a/verify_layout.tx
Updated button for better cross-browser support.
Changed button colors to websafe blue and white
Added additional padding to button
=> Button Updates

views/email/a/verify_layout.tx
Changing the grey text to standard color for improved readability
=> Removing Grey

lib/DaxMailer/Web/App/Subscriber.pm
=> 500 inappropriate for input validation failures - use 400.

views/email/a/verify_layout.tx
Increased button width to prevent wrapping
=> Button edits

views/email/a/verify_layout.tx
Increased button margin slightly
=> Increase Margin

views/email/a/v2.tx
Added additional padding beneath image.
Changed first paragraph from line breaks to paragraph CSS for better mobile support.
Changed hyperlink in last bullet point so the entire line isn't a hyperlink.
=> Visual Changes

views/email/a/verify_layout.tx
=> Button Padding

views/email/a/v2.tx
I'm going to need a padded cell...
=> Padding Changes

views/email/a/verify_layout.tx
=> Typo Fixes

views/email/a/v1.tx
=> Dreaded EmDash

views/email/a/verify_layout.tx
Patch attempt to either fix or break everything :)
=> Attempted Mobile Patch

views/email/a/v2.tx
- Close paragraph around image 
- Fix typo
=> v2.tx : minor tweaks

views/email/a/layout.tx, views/email/a/v1.tx, views/email/a/v2.tx, views/email/a/v3.tx, views/email/a/verify_layout.tx
As discussed, a branch so that we can verify this via our dev instance.
/cc @AdamSC1-ddg
=> responsive layout for mobile - test

bin/migrate_ddgc.pl, lib/Dancer2/Plugin/DaxMailer/Config.pm, lib/DaxMailer/Schema/Result/Subscriber.pm, lib/DaxMailer/Script/MigrateDDGC.pm
Migrate:
- Subscribers
- Bounces
- Logs
Procedure:
- `carton exec bin/migrate_ddgc.pl`
Cc: @jkv @MariagraziaAlastra
=> Migrate ddgc data to daxmailer

lib/DaxMailer/Schema/ResultSet/Bang.pm, lib/DaxMailer/Web/App/Bang.pm, t/bang.t
Cc: @andrey-p 
Testing:
Assuming a default dev instance on port 5666:
- Create a testing publisher setup which posts to http://$your_dev_node:5666/nb/newbang - [line](https://github.com/duckduckgo/duckduckgo-publisher/blob/master/share/site/duckduckgo/newbang.tx#L215)
- Add some invalid !bangs
- `sqlite3 ~/daxmailer.sqlite`
- `select * from bang;`
- None of the invalid bangs added in steps above should be in your table.
=> Filter out invalid bangs.

lib/DaxMailer/Web/App/Subscriber.pm
Testing:
- Visit /s/form
- Requesting 'page' in the parameters should give you the landing page, otherwise a success/failure message (OK/NOT OK)
This is so POSTs from https://github.com/duckduckgo/duckduckgo-publisher/pull/315 have somewhere to go.
=> Basic landing page for non-AJAX signups

bin/verify_last_send.pl, lib/DaxMailer/Schema/ResultSet/Subscriber/MailLog.pm, lib/DaxMailer/Script/VerifyLastSend.pm
```
$ carton exec bin/verify_last_send.pl
Failure
$ echo $?
2
$ carton exec bin/subscriber_mail.pl --verify
$ carton exec bin/verify_last_send.pl 
Success
$ echo $?
0
```
=> Check verify mail runs send

bin/git_pull_dev.sh
=> Script to regularly git pull, install new dependencies, update db schema

lib/DaxMailer/Schema.pm, lib/DaxMailer/Schema/Result/Subscriber/MailLog.pm, sql/DaxMailer-Schema-3-4-PostgreSQL.sql, sql/DaxMailer-Schema-3-4-SQLite.sql, sql/DaxMailer-Schema-4-PostgreSQL.sql, sql/DaxMailer-Schema-4-SQLite.sql
This restriction did not make a huge amount of sense and is getting in the way of incoming new content.
=> Update email id to text blob from char(1)

lib/DaxMailer/Script/SubscriberMailer.pm, lib/DaxMailer/Web/App/Subscriber.pm, views/email/testrun.tx
It's clunky as hell, but it allows:
- Pick the origin flow
- Set a 'From' field (not required)
- Send a single email
=> New test run form

lib/DaxMailer/Script/SubscriberMailer.pm, views/email/a/10.tx
Here's the first one of the second round of mails. Image is yet to be uploaded.
=> Mail content: Newsletter no. 10

lib/DaxMailer/Script/SubscriberMailer.pm, views/email/a/10.tx, views/email/a/11.tx, views/email/a/12.tx, views/email/a/13.tx, views/email/a/14.tx, views/email/a/15.tx
@jbarrett Mind double-checking these before I give them a test?
=> Added drafts for round 2 mails

lib/DaxMailer/Script/SubscriberMailer.pm
Not currently needed because the mail series will continue with round 2.
=> Removed 'was it useful' end-of-round-1 mail

views/email/a/10.tx, views/email/a/layout.tx
* Deleted an unnecessary closing tag
* Added a style for lists
=> Newsletter: Small tweaks

lib/DaxMailer/Schema/Result/Subscriber.pm, lib/DaxMailer/Schema/ResultSet/Subscriber.pm, lib/DaxMailer/Script/SubscriberMailer.pm, t/subscribers.t
=> Use last sent mail to schedule next send

lib/DaxMailer/Schema/Result/Subscriber.pm, lib/DaxMailer/Schema/ResultSet/Subscriber.pm, lib/DaxMailer/Schema/ResultSet/Subscriber/Bounce.pm
=> Hotfix: Add email clauses to restrict inner queries to sets relevant to outer queries

views/email/a/1.tx, views/email/a/10.tx, views/email/a/11.tx, views/email/a/12.tx, views/email/a/13.tx, views/email/a/14.tx, views/email/a/15.tx, views/email/a/1b.tx, views/email/a/1c.tx, views/email/a/2.tx, views/email/a/3.tx, views/email/a/4.tx, views/email/a/5.tx, views/email/a/6.tx, views/email/a/7.tx, views/email/a/signature.tx
This is done by removing the links from the signature and putting them manually in each content file, in order to add individual blog links.
=> Mail content: Added link to blog posts in footer

views/email/a/11.tx
Content only - self-merging like a boss...
=> Mail content: Updated blog link

views/email/a/layout.tx, views/email/a/signup_preamble.tx
* In intro paragraph of very first email
* In footer for all emails
=> Made unsubscribe option more obvious

lib/DaxMailer/Script/SubscriberMailer.pm, t/content.t, t/spread_closed.t
This change silently drops subscribers to campaign 'c'. Hopefully new unit test makes it clear what should be happening. Thanks!
=> Stop accepting spread subscriptions

lib/DaxMailer/Script/SubscriberMailer.pm
=> Changing source domain of email address

views/email/a/20.tx, views/email/a/21.tx, views/email/a/22.tx
New emails for round 3 of the newsletter. Content only so self-merging.
/cc @jbarrett
=> Added new email content

cpanfile, cpanfile.snapshot, lib/Dancer2/Plugin/DaxMailer/Config.pm, lib/DaxMailer/Base/Script/ServiceEmail.pm, lib/DaxMailer/Util/Email.pm
=> Support for Mailgun API

views/email/a/1_common.tx, views/email/a/20.tx, views/email/a/21.tx, views/email/a/22.tx
=> Small fixes to image URLs

views/email/a/23.tx, views/email/a/24.tx
Content only - self-merging.
/cc @jbarrett
=> Added two new emails

lib/DaxMailer/Script/SubscriberMailer.pm, views/email/a/25.tx
=> Added new email to scheduler

lib/DaxMailer/Script/SubscriberMailer.pm, views/email/a/27.tx
=> Added final email for survey

lib/DaxMailer/Script/SubscriberMailer.pm, views/email/oneoff/extension.tx
=> Added content and subject for oneoff email

lib/DaxMailer/Script/SubscriberMailer.pm, t/oneoff.t, views/email/oneoff/crowdfunding.tx
This is to add another oneoff email for the last week of the privacy donations campaign.
@jbarrett Does this look like the right way to add it?
=> Added mail for crowdfunding announcement

views/email/a/22.tx
URL in content only, so self-merging.
/cc @jbarrett
=> Updated URL for speed test site

views/email/a/layout.tx, views/email/a/unsub.tx, views/email/a/verify.tx, views/email/a/verify_layout.tx, views/email/unsub.tx, views/email/verify.tx, views/layouts/mail.tx
=> Format the address properly in the confirmation.

views/email/a/21.tx
Also updated messaging paragraph
=> Added alternative to Google Groups

lib/DaxMailer/Schema.pm, lib/DaxMailer/Schema/Result/Bang.pm, lib/DaxMailer/Schema/ResultSet/Bang.pm, sql/DaxMailer-Schema-4-5-PostgreSQL.sql, sql/DaxMailer-Schema-4-5-SQLite.sql, sql/DaxMailer-Schema-5-PostgreSQL.sql, sql/DaxMailer-Schema-5-SQLite.sql, t/bang.t
Updates DaxMailer to match the upcoming changes to the newbang form.
=> Update bang submission process

views/email/a/25.tx
Content only so self-merging.
/cc @jbarrett
=> Fixed iOS Onion Browser URL

lib/DaxMailer/Schema/ResultSet/Subscriber.pm, lib/DaxMailer/Script/DeletePCCGraduated.pm
=> Fix deleting older subscribers (29 weeks and older, not just created exactly 29 weeks ago)

views/email/a/layout.tx, views/email/a/signature.tx
Adding a callout for the new email forwarding addresses after Dax's signature.
=> Add callout after signature

views/email/a/layout.tx
- Make the header image responsive
- Remove white borders (fixes dark theme in Outlook)
=> Privacy Crash Course header refinements
